"use client";

import jsPDF from "jspdf";
import { motion, AnimatePresence } from "framer-motion";
import {
  Sparkles,
  Plane,
  MapPin,
  Compass,
  Download,
  Trash2,
  Clock,
  ChevronDown,
  Zap,
  Globe,
  Star,
  Share2,
  CheckCheck,
  Sun,
  Moon,
} from "lucide-react";

import ParticlesBackground from "@/components/ParticlesBackground";
import TripMap from "@/components/TripMap";
import WeatherWidget from "@/components/WeatherWidget";
import BudgetChart from "@/components/BudgetChart";
import { useState, useEffect, useRef } from "react";
import { useUser, SignInButton, UserButton } from "@clerk/nextjs";

const MOODS = [
  { label: "Adventure", emoji: "🧗" },
  { label: "Luxury", emoji: "💎" },
  { label: "Relax", emoji: "🌿" },
  { label: "Romantic", emoji: "🌹" },
  { label: "Cyberpunk", emoji: "🤖" },
];

const STATS = [
  { value: "10K+", label: "Trips Planned" },
  { value: "180+", label: "Destinations" },
  { value: "4.9★", label: "User Rating" },
];

const FEATURES = [
  { icon: "⚡", title: "AI-Powered", desc: "Instant itineraries generated by Groq LLaMA 3.3 70B" },
  { icon: "🗺️", title: "Interactive Maps", desc: "See your destination on a live dark-themed map" },
  { icon: "☁️", title: "Live Weather", desc: "5-day forecast fetched in real-time for your trip" },
  { icon: "📄", title: "PDF Export", desc: "Download a clean, shareable itinerary PDF" },
  { icon: "💰", title: "Budget Aware", desc: "Smart budget breakdown with visual pie chart" },
  { icon: "💎", title: "Hidden Gems", desc: "Discover secret spots locals actually visit" },
];

const DESTINATIONS = [
  { city: "Tokyo", flag: "🇯🇵" },
  { city: "Paris", flag: "🇫🇷" },
  { city: "Dubai", flag: "🇦🇪" },
  { city: "Bali", flag: "🇮🇩" },
  { city: "New York", flag: "🇺🇸" },
  { city: "Santorini", flag: "🇬🇷" },
  { city: "Maldives", flag: "🇲🇻" },
  { city: "Kyoto", flag: "🇯🇵" },
  { city: "Barcelona", flag: "🇪🇸" },
  { city: "Cape Town", flag: "🇿🇦" },
  { city: "Istanbul", flag: "🇹🇷" },
  { city: "Singapore", flag: "🇸🇬" },
];

// Safely convert any Gemini response value to a renderable string
const extractText = (val: any): string => {
  if (typeof val === "string") return val;
  if (val === null || val === undefined) return "";
  if (typeof val === "object") {
    // Handle common shapes Gemini returns
    return (
      val.description ||
      val.item ||
      val.name ||
      val.text ||
      val.activity ||
      val.tip ||
      val.gem ||
      Object.values(val).filter((v) => typeof v === "string").join(" — ") ||
      JSON.stringify(val)
    );
  }
  return String(val);
};

const extractActivity = (activity: any): { time?: string; text: string } => {
  if (typeof activity === "string") return { text: activity };
  if (typeof activity === "object" && activity !== null) {
    const text =
      activity.description ||
      activity.activity ||
      activity.item ||
      activity.text ||
      activity.name ||
      Object.values(activity)
        .filter((v) => typeof v === "string" && !activity.time?.includes(v as string))
        .join(" ");
    return { time: activity.time, text };
  }
  return { text: String(activity) };
};

export default function Home() {
  const { isLoaded, isSignedIn, user } = useUser();
  const [mousePosition, setMousePosition] = useState({ x: 0, y: 0 });

  const [destination, setDestination] = useState("");
  const [budget, setBudget] = useState("");
  const [days, setDays] = useState("");
  const [mood, setMood] = useState("Adventure");

  const [loading, setLoading] = useState(false);
  const [result, setResult] = useState<any>(null);
  const [tripHistory, setTripHistory] = useState<any[]>([]);
  const [apiError, setApiError] = useState<string | null>(null);
  const [copied, setCopied] = useState(false);
  const [lightMode, setLightMode] = useState(false);

  const formRef = useRef<HTMLDivElement>(null);

  // Apply light-mode class to <html> so :root CSS vars cascade everywhere
  useEffect(() => {
    if (lightMode) {
      document.documentElement.classList.add("light-mode");
    } else {
      document.documentElement.classList.remove("light-mode");
    }
  }, [lightMode]);

  // Save trip — cloud if signed in, localStorage fallback
  const saveTripToHistory = async (tripData: any) => {
    if (isSignedIn) {
      try {
        const res = await fetch("/api/trips", {
          method: "POST",
          headers: { "Content-Type": "application/json" },
          body: JSON.stringify({
            destination: tripData.destination,
            title: tripData.title,
            trip_data: tripData,
          }),
        });
        if (res.ok) {
          const { trip } = await res.json();
          setTripHistory((prev: any[]) => [{ ...tripData, supabase_id: trip.id }, ...prev].slice(0, 20));
          return;
        }
      } catch {}
    }
    // localStorage fallback
    const existingTrips = JSON.parse(localStorage.getItem("tripHistory") || "[]");
    const updatedTrips = [tripData, ...existingTrips].slice(0, 10);
    localStorage.setItem("tripHistory", JSON.stringify(updatedTrips));
    setTripHistory(updatedTrips);
  };

  // Load trips — cloud if signed in, localStorage fallback
  useEffect(() => {
    if (!isLoaded) return;
    if (isSignedIn) {
      fetch("/api/trips")
        .then((r) => r.json())
        .then(({ trips }) => {
          if (trips) {
            setTripHistory(
              trips.map((t: any) => ({ ...t.trip_data, supabase_id: t.id, created_at: t.created_at }))
            );
          }
        })
        .catch(() => {});
    } else {
      const savedTrips = JSON.parse(localStorage.getItem("tripHistory") || "[]");
      setTripHistory(savedTrips);
    }
  }, [isLoaded, isSignedIn]);

  const deleteTrip = async (index: number) => {
    const trip = tripHistory[index];
    if (isSignedIn && trip?.supabase_id) {
      try {
        await fetch(`/api/trips?id=${trip.supabase_id}`, { method: "DELETE" });
      } catch {}
    } else {
      const updatedTrips = tripHistory.filter((_: any, i: number) => i !== index);
      localStorage.setItem("tripHistory", JSON.stringify(updatedTrips));
    }
    setTripHistory((prev: any[]) => prev.filter((_: any, i: number) => i !== index));
  };

  const handleMouseMove = (e: any) => {
    setMousePosition({ x: e.clientX, y: e.clientY });
  };

  const scrollToForm = () => {
    formRef.current?.scrollIntoView({ behavior: "smooth" });
  };

  const shareTrip = async () => {
    if (!result) return;
    const text = `🌍 ${result.title}\n💰 ${result.budget}\n\nGenerated by Planora AI — https://localhost:3000`;
    try {
      await navigator.clipboard.writeText(text);
      setCopied(true);
      setTimeout(() => setCopied(false), 2500);
    } catch {
      // fallback
      const el = document.createElement("textarea");
      el.value = text;
      document.body.appendChild(el);
      el.select();
      document.execCommand("copy");
      document.body.removeChild(el);
      setCopied(true);
      setTimeout(() => setCopied(false), 2500);
    }
  };

  const generateTrip = async () => {
    if (!destination.trim()) {
      setApiError("Please enter a destination.");
      return;
    }
    try {
      setLoading(true);
      setResult(null);
      setApiError(null);

      const response = await fetch("/api/generate-trip", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ destination, budget, days, mood }),
      });

      const data = await response.json();

      if (!data.result) {
        console.error("API Error:", data);
        // Parse friendly message from Gemini error JSON
        let msg = "Failed to generate trip. Please try again.";
        try {
          const errObj = JSON.parse(data.error);
          if (errObj?.error?.code === 429) {
            msg = "🚫 API quota exceeded. The free-tier limit has been reached. Please check your Gemini API billing or try again later.";
          } else {
            msg = errObj?.error?.message || data.error || msg;
          }
        } catch {
          if (typeof data.error === "string" && data.error.includes("429")) {
            msg = "🚫 API quota exceeded. The free-tier limit has been reached. Please check your Gemini API billing or try again later.";
          } else if (data.error) {
            msg = data.error;
          }
        }
        setApiError(msg);
        return;
      }

      const cleaned = data.result
        .replace(/```json/g, "")
        .replace(/```/g, "")
        .trim();

      const parsed = JSON.parse(cleaned);

      setResult(parsed);
      saveTripToHistory(parsed);

      setTimeout(() => {
        document.getElementById("trip-result")?.scrollIntoView({ behavior: "smooth" });
      }, 400);
    } catch (err) {
      console.error("Error:", err);
      setApiError("Something went wrong while generating your trip. Please try again.");
    } finally {
      setLoading(false);
    }
  };

  const downloadPDF = () => {
    if (!result) return;
    const doc = new jsPDF();
    const pageWidth = doc.internal.pageSize.getWidth();
    const margin = 14;
    const contentWidth = pageWidth - margin * 2;
    let y = 22;

    // ── Title
    doc.setFontSize(24);
    doc.setFont("helvetica", "bold");
    doc.setTextColor(20, 20, 40);
    doc.text(result.title || "Travel Itinerary", margin, y);
    y += 10;

    // ── Divider line
    doc.setDrawColor(0, 180, 220);
    doc.setLineWidth(0.8);
    doc.line(margin, y, pageWidth - margin, y);
    y += 8;

    // ── Budget (wrapped)
    doc.setFontSize(11);
    doc.setFont("helvetica", "normal");
    doc.setTextColor(80, 80, 100);
    const budgetLines = doc.splitTextToSize(`Budget: ${result.budget}`, contentWidth);
    doc.text(budgetLines, margin, y);
    y += budgetLines.length * 6 + 10;

    // ── Days
    result.days?.forEach((day: any) => {
      if (y > 260) { doc.addPage(); y = 22; }

      doc.setFontSize(13);
      doc.setFont("helvetica", "bold");
      doc.setTextColor(30, 30, 60);
      doc.text(`Day ${day.day}`, margin, y);
      y += 8;

      doc.setFontSize(10.5);
      doc.setFont("helvetica", "normal");
      doc.setTextColor(60, 60, 80);

      day.activities?.forEach((activity: any) => {
        const text =
          typeof activity === "string"
            ? activity
            : `${activity.time ? activity.time + "  —  " : ""}${activity.description || extractText(activity)}`;
        const lines = doc.splitTextToSize(`\u2022  ${text}`, contentWidth - 4);
        if (y > 272) { doc.addPage(); y = 22; }
        doc.text(lines, margin + 2, y);
        y += lines.length * 6;
      });
      y += 6;
    });

    // ── Section helper
    const section = (title: string, items: any[]) => {
      if (y > 248) { doc.addPage(); y = 22; }
      y += 4;
      doc.setFontSize(13);
      doc.setFont("helvetica", "bold");
      doc.setTextColor(30, 30, 60);
      doc.text(title, margin, y);
      y += 8;

      doc.setFontSize(10.5);
      doc.setFont("helvetica", "normal");
      doc.setTextColor(60, 60, 80);
      items?.forEach((item: any) => {
        const text = extractText(item);
        const lines = doc.splitTextToSize(`\u2022  ${text}`, contentWidth - 4);
        if (y > 272) { doc.addPage(); y = 22; }
        doc.text(lines, margin + 2, y);
        y += lines.length * 6;
      });
      y += 6;
    };

    section("FOOD RECOMMENDATIONS", result.food);
    section("HIDDEN GEMS", result.hiddenGems);
    section("TRAVEL TIPS", result.tips);

    doc.save(`${destination || "trip"}-itinerary.pdf`);
  };

  return (
    <main
      onMouseMove={handleMouseMove}
      className="relative min-h-screen overflow-hidden"
      style={{ background: "var(--bg-deep)" }}
    >
      {/* Canvas Particles */}
      <ParticlesBackground />

      {/* Aurora Background Orbs */}
      <div className="absolute inset-0 overflow-hidden pointer-events-none">
        <div
          className="aurora-orb"
          style={{
            width: 700,
            height: 700,
            top: "-15%",
            left: "-10%",
            background: "radial-gradient(circle, rgba(0,212,255,0.12) 0%, transparent 70%)",
          }}
        />
        <div
          className="aurora-orb"
          style={{
            width: 600,
            height: 600,
            top: "30%",
            right: "-15%",
            background: "radial-gradient(circle, rgba(155,89,255,0.12) 0%, transparent 70%)",
            animationDelay: "-7s",
          }}
        />
        <div
          className="aurora-orb"
          style={{
            width: 500,
            height: 500,
            bottom: "-10%",
            left: "30%",
            background: "radial-gradient(circle, rgba(0,180,255,0.08) 0%, transparent 70%)",
            animationDelay: "-14s",
          }}
        />
      </div>

      {/* Mouse Glow — desktop only, stays at 0,0 on touch */}
      <div
        className="pointer-events-none absolute z-0 rounded-full transition-all duration-500 hidden md:block"
        style={{
          width: 500,
          height: 500,
          left: mousePosition.x - 250,
          top: mousePosition.y - 250,
          background: "radial-gradient(circle, rgba(0,212,255,0.06) 0%, transparent 70%)",
        }}
      />

      {/* Floating Icons */}
      <div className="float-slow absolute left-[6%] top-[22%] z-10 hidden md:block">
        <div className="glass-card rounded-2xl p-4 glow-blue" style={{ border: "1px solid rgba(0,212,255,0.2)" }}>
          <Plane className="text-[#00d4ff]" size={24} />
        </div>
      </div>
      <div className="float-medium absolute right-[8%] top-[50%] z-10 hidden md:block">
        <div className="glass-card rounded-2xl p-4 glow-violet" style={{ border: "1px solid rgba(155,89,255,0.2)" }}>
          <MapPin className="text-[#9b59ff]" size={24} />
        </div>
      </div>
      <div className="float-fast absolute bottom-[20%] left-[12%] z-10 hidden md:block">
        <div className="glass-card rounded-2xl p-4" style={{ border: "1px solid rgba(255,255,255,0.1)" }}>
          <Compass className="text-[#7ec8e3]" size={24} />
        </div>
      </div>

      {/* ═══ NAVBAR ═══ */}
      <motion.nav
        initial={{ opacity: 0, y: -30 }}
        animate={{ opacity: 1, y: 0 }}
        transition={{ duration: 0.6 }}
        className="fixed left-1/2 top-4 z-50 w-[94%] max-w-7xl -translate-x-1/2"
      >
        <div
          className="glass-card rounded-full px-4 py-3 sm:px-6 sm:py-4 flex items-center justify-between"
          style={{ border: "1px solid rgba(255,255,255,0.18)" }}
        >
          <span className="font-space text-xl sm:text-2xl font-bold tracking-widest text-gradient">
            PLANORA
          </span>

          <div className="flex items-center gap-2 sm:gap-3">
            {/* Light/Dark toggle */}
            <button
              onClick={() => setLightMode((m) => !m)}
              className="flex items-center justify-center w-9 h-9 rounded-full transition-all duration-300"
              style={{
                background: lightMode ? "rgba(255,200,0,0.12)" : "rgba(0,212,255,0.08)",
                border: lightMode ? "1px solid rgba(255,200,0,0.3)" : "1px solid rgba(0,212,255,0.2)",
                color: lightMode ? "#f5c518" : "#00d4ff",
              }}
              title={lightMode ? "Switch to Dark" : "Switch to Light"}
            >
              {lightMode ? <Sun size={15} /> : <Moon size={15} />}
            </button>

            {/* Clerk Auth */}
            {isLoaded && (
              isSignedIn ? (
                <div className="flex items-center gap-2">
                  <span className="text-sm hidden sm:block" style={{ color: "var(--text-secondary)" }}>
                    {user?.firstName || user?.emailAddresses?.[0]?.emailAddress?.split("@")[0]}
                  </span>
                  <UserButton
                    appearance={{
                      elements: {
                        avatarBox: "w-9 h-9 ring-2 ring-cyan-400/30 hover:ring-cyan-400/60 transition-all",
                      },
                    }}
                  />
                </div>
              ) : (
                <SignInButton mode="modal">
                  <button
                    className="flex items-center gap-2 rounded-full px-5 py-2 text-sm font-semibold transition-all duration-200"
                    style={{
                      background: "rgba(0,212,255,0.1)",
                      border: "1px solid rgba(0,212,255,0.35)",
                      color: "#00d4ff",
                    }}
                    onMouseEnter={(e) => {
                      (e.currentTarget as HTMLButtonElement).style.background = "rgba(0,212,255,0.2)";
                    }}
                    onMouseLeave={(e) => {
                      (e.currentTarget as HTMLButtonElement).style.background = "rgba(0,212,255,0.1)";
                    }}
                  >
                    <span>⚡</span> Sign In
                  </button>
                </SignInButton>
              )
            )}

            <button
              onClick={scrollToForm}
              className="btn-primary rounded-full px-4 py-2 text-xs sm:px-6 sm:py-2.5 sm:text-sm hidden sm:inline-flex"
            >
              ✦ Start Planning
            </button>
          </div>
        </div>
      </motion.nav>

      {/* ═══ HERO ═══ */}
      <section className="relative z-10 flex min-h-screen flex-col items-center justify-center px-4 sm:px-6 pt-24 sm:pt-32 text-center">
        {/* Badge */}
        <motion.div
          initial={{ opacity: 0, scale: 0.9 }}
          animate={{ opacity: 1, scale: 1 }}
          transition={{ delay: 0.2 }}
          className="mb-8 inline-flex items-center gap-2 rounded-full px-5 py-2 text-sm font-medium"
          style={{
            background: "rgba(0,212,255,0.08)",
            border: "1px solid rgba(0,212,255,0.25)",
            color: "#00d4ff",
          }}
        >
          <Zap size={14} />
          Powered by Groq AI
        </motion.div>

        {/* Headline */}
        <motion.h1
          initial={{ opacity: 0, y: 30 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ delay: 0.3, duration: 0.8 }}
          className="font-space font-bold leading-none tracking-tight"
          style={{ fontSize: "clamp(2.2rem, 10vw, 9rem)" }}
        >
          <span style={{ color: "var(--text-primary)" }}>PLAN THE</span>
          <br />
          <span className="text-gradient">FUTURE</span>
          <br />
          <span style={{ color: "var(--text-primary)" }}>OF TRAVEL</span>
        </motion.h1>

        {/* Subheadline */}
        <motion.p
          initial={{ opacity: 0 }}
          animate={{ opacity: 1 }}
          transition={{ delay: 0.6 }}
          className="mt-6 max-w-2xl text-sm sm:text-lg leading-relaxed px-2 sm:px-0"
          style={{ color: "var(--text-secondary)" }}
        >
          Generate cinematic AI-powered itineraries, discover hidden gems,
          and experience futuristic trip planning — all in seconds.
        </motion.p>

        {/* CTA Buttons */}
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ delay: 0.8 }}
          className="mt-10 flex flex-wrap gap-4 justify-center"
        >
          <button
            onClick={scrollToForm}
            className="btn-primary rounded-2xl px-7 py-3 text-sm sm:px-10 sm:py-4 sm:text-base"
          >
            ✦ Start Planning
          </button>
          <button
            className="rounded-2xl px-7 py-3 text-sm sm:px-10 sm:py-4 sm:text-base font-medium transition-all duration-200"
            style={{
              background: "rgba(255,255,255,0.04)",
              border: "1px solid rgba(255,255,255,0.12)",
              color: "var(--text-primary)",
            }}
            onMouseEnter={(e) => {
              (e.currentTarget as HTMLButtonElement).style.background = "rgba(255,255,255,0.08)";
              (e.currentTarget as HTMLButtonElement).style.borderColor = "rgba(0,212,255,0.3)";
            }}
            onMouseLeave={(e) => {
              (e.currentTarget as HTMLButtonElement).style.background = "rgba(255,255,255,0.04)";
              (e.currentTarget as HTMLButtonElement).style.borderColor = "rgba(255,255,255,0.12)";
            }}
          >
            Watch Demo
          </button>
        </motion.div>

        {/* Stats */}
        <motion.div
          initial={{ opacity: 0 }}
          animate={{ opacity: 1 }}
          transition={{ delay: 1 }}
          className="mt-10 flex gap-6 sm:gap-12 justify-center"
        >
          {STATS.map((stat) => (
            <div key={stat.label} className="text-center">
              <div className="font-space text-2xl sm:text-3xl font-bold text-gradient">{stat.value}</div>
              <div className="mt-1 text-[10px] sm:text-xs" style={{ color: "var(--text-muted)" }}>
                {stat.label}
              </div>
            </div>
          ))}
        </motion.div>

        {/* Scroll indicator */}
        <motion.button
          onClick={scrollToForm}
          initial={{ opacity: 0 }}
          animate={{ opacity: 1 }}
          transition={{ delay: 1.2 }}
          className="mt-12 flex flex-col items-center gap-2 cursor-pointer"
          style={{ color: "var(--text-muted)" }}
        >
          <span className="text-xs tracking-widest font-space">SCROLL DOWN</span>
          <motion.div
            animate={{ y: [0, 6, 0] }}
            transition={{ duration: 1.5, repeat: Infinity }}
          >
            <ChevronDown size={20} />
          </motion.div>
        </motion.button>
      </section>

      {/* ═══ FEATURES SECTION ═══ */}
      <section className="relative z-10 px-6 pb-20">
        <motion.div
          initial={{ opacity: 0, y: 40 }}
          whileInView={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.8 }}
          viewport={{ once: true }}
          className="mx-auto max-w-5xl"
        >
          <div className="mb-12 text-center">
            <div
              className="inline-flex items-center gap-2 rounded-full px-4 py-1.5 text-xs font-semibold tracking-widest font-space mb-4"
              style={{
                background: "rgba(0,212,255,0.08)",
                border: "1px solid rgba(0,212,255,0.2)",
                color: "#00d4ff",
              }}
            >
              <Sparkles size={12} />
              WHY PLANORA
            </div>
            <h2 className="font-space text-3xl md:text-4xl font-bold" style={{ color: "var(--text-primary)" }}>
              Everything you need to
              <span className="text-gradient"> plan perfectly</span>
            </h2>
          </div>

          <div className="grid gap-4 sm:grid-cols-2 md:grid-cols-3">
            {FEATURES.map((f, i) => (
              <motion.div
                key={f.title}
                initial={{ opacity: 0, y: 20 }}
                whileInView={{ opacity: 1, y: 0 }}
                transition={{ delay: i * 0.08, duration: 0.5 }}
                viewport={{ once: true }}
                whileHover={{ y: -4 }}
                className="glass-card glass-card-hover rounded-2xl p-5"
                style={{ border: "1px solid rgba(255,255,255,0.07)" }}
              >
                <div
                  className="mb-3 inline-flex h-11 w-11 items-center justify-center rounded-xl text-2xl"
                  style={{ background: "rgba(0,212,255,0.08)", border: "1px solid rgba(0,212,255,0.15)" }}
                >
                  {f.icon}
                </div>
                <h3 className="font-space text-base font-semibold mb-1" style={{ color: "var(--text-primary)" }}>
                  {f.title}
                </h3>
                <p className="text-sm leading-relaxed" style={{ color: "var(--text-secondary)" }}>
                  {f.desc}
                </p>
              </motion.div>
            ))}
          </div>
        </motion.div>
      </section>

      {/* ═══ AI TRIP GENERATOR ═══ */}
      <section className="relative z-10 px-6 pb-32" ref={formRef}>
        <motion.div
          initial={{ opacity: 0, y: 60 }}
          whileInView={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.9 }}
          viewport={{ once: true }}
          className="mx-auto max-w-4xl"
        >
          {/* Section label */}
          <div className="mb-10 text-center">
            <div
              className="inline-flex items-center gap-2 rounded-full px-4 py-1.5 text-xs font-semibold tracking-widest font-space mb-4"
              style={{
                background: "rgba(155,89,255,0.1)",
                border: "1px solid rgba(155,89,255,0.25)",
                color: "#9b59ff",
              }}
            >
              <Sparkles size={12} />
              AI GENERATOR
            </div>
            <h2
              className="font-space text-2xl sm:text-4xl font-bold"
              style={{ color: "var(--text-primary)" }}
            >
              Generate Your AI Journey
            </h2>
            <p className="mt-3" style={{ color: "var(--text-secondary)" }}>
              Tell us your dream — we&apos;ll build the perfect itinerary.
            </p>
          </div>

          {/* Form Card */}
          <div
            className="glass-card rounded-3xl p-4 sm:p-8 md:p-10"
            style={{
              border: "1px solid rgba(0,212,255,0.12)",
              boxShadow: "0 0 60px rgba(0,212,255,0.05), 0 0 120px rgba(155,89,255,0.04)",
            }}
          >
            <div className="grid gap-6 md:grid-cols-2">
              {/* Destination */}
              <div>
                <label
                  className="mb-2 flex items-center gap-2 text-sm font-medium font-space"
                  style={{ color: "var(--text-secondary)" }}
                >
                  <Globe size={14} />
                  Destination
                </label>
                <input
                  type="text"
                  id="destination-input"
                  placeholder="Tokyo, Bali, Paris..."
                  value={destination}
                  onChange={(e) => setDestination(e.target.value)}
                  className="input-dark w-full rounded-xl px-4 py-3.5 text-sm"
                />
              </div>

              {/* Budget */}
              <div>
                <label
                  className="mb-2 flex items-center gap-2 text-sm font-medium font-space"
                  style={{ color: "var(--text-secondary)" }}
                >
                  <Star size={14} />
                  Budget
                </label>
                <input
                  type="text"
                  id="budget-input"
                  placeholder="₹50,000 / $600..."
                  value={budget}
                  onChange={(e) => setBudget(e.target.value)}
                  className="input-dark w-full rounded-xl px-4 py-3.5 text-sm"
                />
              </div>

              {/* Days */}
              <div>
                <label
                  className="mb-2 flex items-center gap-2 text-sm font-medium font-space"
                  style={{ color: "var(--text-secondary)" }}
                >
                  <Clock size={14} />
                  Duration (days)
                </label>
                <input
                  type="number"
                  id="days-input"
                  placeholder="5"
                  min="1"
                  max="30"
                  value={days}
                  onChange={(e) => setDays(e.target.value)}
                  className="input-dark w-full rounded-xl px-4 py-3.5 text-sm"
                />
              </div>

              {/* Mood — spanning full width on md */}
              <div className="md:col-span-2">
                <label
                  className="mb-3 flex items-center gap-2 text-sm font-medium font-space"
                  style={{ color: "var(--text-secondary)" }}
                >
                  <Sparkles size={14} />
                  Travel Mood
                </label>
                <div className="flex flex-wrap gap-3">
                  {MOODS.map((m) => (
                    <button
                      key={m.label}
                      id={`mood-${m.label.toLowerCase()}`}
                      onClick={() => setMood(m.label)}
                      className={`mood-pill ${mood === m.label ? "active" : ""}`}
                    >
                      {m.emoji} {m.label}
                    </button>
                  ))}
                </div>
              </div>
            </div>

            {/* Generate Button */}
            <div className="mt-8 text-center">
              <button
                id="generate-btn"
                onClick={generateTrip}
                disabled={loading}
                className="btn-primary rounded-2xl w-full sm:w-auto px-8 py-3.5 sm:px-14 sm:py-4 text-sm sm:text-base"
              >
                {loading ? (
                  <span className="flex items-center gap-3">
                    <span
                      className="inline-block h-4 w-4 animate-spin rounded-full border-2 border-white/30 border-t-white"
                    />
                    Generating your journey...
                  </span>
                ) : (
                  "✦ Generate AI Trip"
                )}
              </button>
              <p className="mt-3 text-xs" style={{ color: "var(--text-muted)" }}>
                Powered by Groq LLaMA 3.3 · Usually takes 2–5 seconds
              </p>
            </div>

            {/* Error Banner */}
            <AnimatePresence>
              {apiError && (
                <motion.div
                  initial={{ opacity: 0, y: -10 }}
                  animate={{ opacity: 1, y: 0 }}
                  exit={{ opacity: 0, y: -10 }}
                  className="mt-6 flex items-start gap-3 rounded-2xl px-5 py-4 text-sm"
                  style={{
                    background: "rgba(255, 80, 80, 0.08)",
                    border: "1px solid rgba(255, 80, 80, 0.25)",
                    color: "#ff8080",
                  }}
                >
                  <span className="mt-0.5 shrink-0 text-base">⚠️</span>
                  <span>{apiError}</span>
                  <button
                    onClick={() => setApiError(null)}
                    className="ml-auto shrink-0 opacity-60 hover:opacity-100 transition-opacity"
                  >
                    ✕
                  </button>
                </motion.div>
              )}
            </AnimatePresence>

            {/* Loading Skeleton */}
            <AnimatePresence>
              {loading && (
                <motion.div
                  initial={{ opacity: 0, height: 0 }}
                  animate={{ opacity: 1, height: "auto" }}
                  exit={{ opacity: 0, height: 0 }}
                  className="mt-8 space-y-3 overflow-hidden"
                >
                  <div className="skeleton h-6 w-3/4" />
                  <div className="skeleton h-4 w-full" />
                  <div className="skeleton h-4 w-5/6" />
                  <div className="skeleton h-4 w-4/5" />
                  <div className="skeleton h-4 w-full" />
                </motion.div>
              )}
            </AnimatePresence>
          </div>

          {/* ═══ TRIP HISTORY ═══ */}
          <AnimatePresence>
            {tripHistory.length > 0 && (
              <motion.div
                initial={{ opacity: 0, y: 20 }}
                animate={{ opacity: 1, y: 0 }}
                className="mt-10"
              >
                <div className="mb-5 flex items-center gap-2">
                  <Clock size={16} style={{ color: "var(--text-muted)" }} />
                  <h3 className="font-space text-lg font-semibold" style={{ color: "var(--text-secondary)" }}>
                    Recent Trips
                  </h3>
                </div>
                <div className="grid gap-3 sm:grid-cols-2 md:grid-cols-3">
                  {tripHistory.slice(0, 6).map((trip, index) => (
                    <motion.div
                      key={index}
                      initial={{ opacity: 0, y: 10 }}
                      animate={{ opacity: 1, y: 0 }}
                      transition={{ delay: index * 0.05 }}
                      whileHover={{ y: -2 }}
                      onClick={() => setResult(trip)}
                      className="glass-card glass-card-hover cursor-pointer rounded-2xl p-4"
                    >
                      <div className="flex items-start justify-between gap-2">
                        <div className="min-w-0 flex-1">
                          <p
                            className="truncate font-space text-sm font-semibold"
                            style={{ color: "var(--text-primary)" }}
                          >
                            {trip.title}
                          </p>
                          <p className="mt-0.5 text-xs" style={{ color: "var(--text-muted)" }}>
                            {trip.budget}
                          </p>
                        </div>
                        <button
                          onClick={(e) => { e.stopPropagation(); deleteTrip(index); }}
                          className="shrink-0 rounded-lg p-1 transition-colors"
                          style={{ color: "var(--text-muted)" }}
                          onMouseEnter={(e) => (e.currentTarget.style.color = "#ff6b6b")}
                          onMouseLeave={(e) => (e.currentTarget.style.color = "var(--text-muted)")}
                        >
                          <Trash2 size={14} />
                        </button>
                      </div>
                    </motion.div>
                  ))}
                </div>
              </motion.div>
            )}
          </AnimatePresence>

          {/* ═══ TRIP RESULT ═══ */}
          <AnimatePresence>
            {result && (
              <motion.div
                id="trip-result"
                initial={{ opacity: 0, y: 40 }}
                animate={{ opacity: 1, y: 0 }}
                transition={{ duration: 0.6 }}
                className="mt-12 overflow-hidden rounded-2xl sm:rounded-3xl"
                style={{
                  border: "1px solid rgba(255,255,255,0.08)",
                  background: "rgba(255,255,255,0.03)",
                  backdropFilter: "blur(20px)",
                }}
              >
                {/* Hero Image */}
                <div className="relative h-44 sm:h-72 w-full overflow-hidden">
                  <img
                    src={`https://loremflickr.com/1200/500/${encodeURIComponent(destination || "travel")},travel`}
                    alt={destination}
                    className="h-full w-full object-cover"
                    onError={(e) => {
                      (e.target as HTMLImageElement).src = `https://picsum.photos/seed/${encodeURIComponent(destination || "travel")}/1200/500`;
                    }}
                  />
                  <div className="absolute inset-0" style={{ background: "linear-gradient(to top, rgba(5,8,17,0.9) 0%, rgba(5,8,17,0.3) 50%, transparent 100%)" }} />
                  <div className="absolute bottom-3 left-4 right-4 sm:bottom-6 sm:left-8 sm:right-8">
                    <h2 className="font-space text-lg sm:text-3xl font-bold" style={{ color: "white" }}>
                      {result.title}
                    </h2>
                    <div
                      className="mt-2 inline-flex items-center gap-2 rounded-full px-4 py-1 text-sm"
                      style={{ background: "rgba(0,212,255,0.2)", color: "#00d4ff", border: "1px solid rgba(0,212,255,0.3)" }}
                    >
                      💰 {result.budget}
                    </div>
                  </div>
                </div>

                <div className="p-4 sm:p-8">
                  {/* Download + Share Buttons */}
                  <div className="mb-8 flex items-center gap-3 flex-wrap">
                    <button
                      id="download-pdf-btn"
                      onClick={downloadPDF}
                      className="flex items-center gap-2 rounded-xl px-5 py-3 text-sm font-semibold font-space transition-all duration-200"
                      style={{
                        background: "rgba(0,200,100,0.12)",
                        border: "1px solid rgba(0,200,100,0.3)",
                        color: "#00c864",
                      }}
                      onMouseEnter={(e) => {
                        (e.currentTarget as HTMLButtonElement).style.background = "rgba(0,200,100,0.2)";
                        (e.currentTarget as HTMLButtonElement).style.boxShadow = "0 0 20px rgba(0,200,100,0.2)";
                      }}
                      onMouseLeave={(e) => {
                        (e.currentTarget as HTMLButtonElement).style.background = "rgba(0,200,100,0.12)";
                        (e.currentTarget as HTMLButtonElement).style.boxShadow = "none";
                      }}
                    >
                      <Download size={16} />
                      Download PDF
                    </button>

                    <button
                      onClick={shareTrip}
                      className="flex items-center gap-2 rounded-xl px-5 py-3 text-sm font-semibold font-space transition-all duration-200"
                      style={{
                        background: copied ? "rgba(0,212,255,0.2)" : "rgba(0,212,255,0.1)",
                        border: `1px solid ${copied ? "rgba(0,212,255,0.5)" : "rgba(0,212,255,0.25)"}`,
                        color: "#00d4ff",
                      }}
                    >
                      {copied ? <CheckCheck size={16} /> : <Share2 size={16} />}
                      {copied ? "Copied!" : "Share Trip"}
                    </button>
                  </div>

                  {/* Map + Weather row */}
                  <div className="mb-8 grid gap-4 md:grid-cols-2">
                    <div>
                      <p className="mb-2 flex items-center gap-2 text-sm font-semibold font-space" style={{ color: "var(--text-secondary)" }}>
                        <MapPin size={14} /> Destination Map
                      </p>
                      <TripMap destination={destination} />
                    </div>
                    <div>
                      <p className="mb-2 flex items-center gap-2 text-sm font-semibold font-space" style={{ color: "var(--text-secondary)" }}>
                        <span>☁️</span> Live Weather
                      </p>
                      <WeatherWidget destination={destination} />
                    </div>
                  </div>

                  {/* Day-by-Day */}
                  <div className="mb-8">
                    <h3 className="mb-6 font-space text-xl font-bold" style={{ color: "var(--text-primary)" }}>
                      📅 Day-by-Day Itinerary
                    </h3>
                    <div className="space-y-5">
                      {result.days?.map((day: any, index: number) => (
                        <motion.div
                          key={index}
                          initial={{ opacity: 0, x: -20 }}
                          animate={{ opacity: 1, x: 0 }}
                          transition={{ delay: index * 0.08 }}
                          className="day-card"
                        >
                          {/* Day number dot */}
                          <div
                            className="absolute left-0 top-1 flex h-4 w-4 items-center justify-center rounded-full text-[10px] font-bold font-space"
                            style={{
                              background: "linear-gradient(135deg, #00d4ff, #9b59ff)",
                              color: "white",
                              fontSize: "9px",
                            }}
                          >
                            {day.day}
                          </div>

                          <div
                            className="rounded-2xl p-5"
                            style={{
                              background: "rgba(255,255,255,0.03)",
                              border: "1px solid rgba(255,255,255,0.06)",
                            }}
                          >
                            <h4 className="mb-3 font-space text-lg font-semibold" style={{ color: "var(--text-primary)" }}>
                              Day {day.day}
                            </h4>
                            <ul className="space-y-2">
                              {day.activities?.map((activity: any, i: number) => {
                                const { time, text } = extractActivity(activity);
                                return (
                                  <li key={i} className="flex items-start gap-2 text-sm" style={{ color: "var(--text-secondary)" }}>
                                    <span style={{ color: "#00d4ff", marginTop: "2px" }}>›</span>
                                    {time ? (
                                      <>
                                        <span className="font-medium font-space shrink-0" style={{ color: "#00d4ff" }}>
                                          {time}
                                        </span>
                                        <span> — {text}</span>
                                      </>
                                    ) : (
                                      <span>{text}</span>
                                    )}
                                  </li>
                                );
                              })}
                            </ul>
                          </div>
                        </motion.div>
                      ))}
                    </div>
                  </div>

                  {/* Budget Chart + Food/Gems/Tips */}
                  {result.budgetBreakdown && (
                    <div className="mb-8">
                      <BudgetChart
                        breakdown={result.budgetBreakdown}
                        totalBudget={result.budget}
                      />
                    </div>
                  )}

                  {/* Food / Hidden Gems / Tips Grid */}
                  <div className="grid gap-5 md:grid-cols-3">
                    {[
                      { title: "🍜 Food Spots", key: "food", color: "#ff8c42", bg: "rgba(255,140,66,0.08)", border: "rgba(255,140,66,0.2)" },
                      { title: "💎 Hidden Gems", key: "hiddenGems", color: "#9b59ff", bg: "rgba(155,89,255,0.08)", border: "rgba(155,89,255,0.2)" },
                      { title: "✈️ Travel Tips", key: "tips", color: "#00d4ff", bg: "rgba(0,212,255,0.08)", border: "rgba(0,212,255,0.2)" },
                    ].map((section) => (
                      <motion.div
                        key={section.key}
                        initial={{ opacity: 0, y: 20 }}
                        animate={{ opacity: 1, y: 0 }}
                        className="rounded-2xl p-5"
                        style={{ background: section.bg, border: `1px solid ${section.border}` }}
                      >
                        <h3 className="mb-4 font-space font-bold" style={{ color: section.color }}>
                          {section.title}
                        </h3>
                        <ul className="space-y-2">
                          {result[section.key]?.map((item: any, i: number) => (
                            <li key={i} className="flex items-start gap-2 text-sm" style={{ color: "var(--text-secondary)" }}>
                              <span style={{ color: section.color }}>•</span>
                              <span>{extractText(item)}</span>
                            </li>
                          ))}
                        </ul>
                      </motion.div>
                    ))}
                  </div>
                </div>
              </motion.div>
            )}
          </AnimatePresence>
        </motion.div>
      </section>

      {/* FOOTER */}
      <footer className="relative z-10 mt-8 border-t" style={{ borderColor: "rgba(255,255,255,0.06)" }}>
        <div className="mx-auto max-w-7xl px-4 sm:px-6 py-10 sm:py-16">
          <div className="grid gap-8 sm:grid-cols-2 md:grid-cols-4">
            <div className="md:col-span-1">
              <span className="font-space text-2xl font-bold tracking-widest text-gradient">PLANORA</span>
              <p className="mt-3 text-sm leading-relaxed" style={{ color: "var(--text-muted)" }}>
                AI-powered travel planning for the future. Generate stunning itineraries in seconds.
              </p>
              <div className="mt-5 flex gap-3">
                {["X", "IG", "YT"].map((s) => (
                  <a key={s} href="#"
                    className="flex h-9 w-9 items-center justify-center rounded-full text-xs font-bold font-space transition-all duration-200"
                    style={{ background: "rgba(255,255,255,0.05)", border: "1px solid rgba(255,255,255,0.08)", color: "var(--text-muted)" }}
                    onMouseEnter={(e) => { (e.currentTarget as HTMLAnchorElement).style.borderColor = "rgba(0,212,255,0.4)"; (e.currentTarget as HTMLAnchorElement).style.color = "#00d4ff"; }}
                    onMouseLeave={(e) => { (e.currentTarget as HTMLAnchorElement).style.borderColor = "rgba(255,255,255,0.08)"; (e.currentTarget as HTMLAnchorElement).style.color = "var(--text-muted)"; }}
                  >{s}</a>
                ))}
              </div>
            </div>

            {[{
              title: "PRODUCT",
              links: ["AI Planner", "Trip History", "PDF Export", "Budget Tools"],
              hoverColor: "#00d4ff",
            }, {
              title: "POPULAR",
              links: ["Tokyo 🇯🇵", "Paris 🇫🇷", "Bali 🇮🇩", "Dubai 🇦🇪"],
              hoverColor: "#9b59ff",
            }, {
              title: "COMPANY",
              links: ["About", "Blog", "Privacy Policy", "Terms of Service"],
              hoverColor: "var(--text-secondary)",
            }].map((col) => (
              <div key={col.title}>
                <h4 className="mb-4 font-space text-sm font-semibold tracking-wider" style={{ color: "var(--text-primary)" }}>
                  {col.title}
                </h4>
                <ul className="space-y-3">
                  {col.links.map((l) => (
                    <li key={l}>
                      <a href="#" className="text-sm transition-colors duration-200" style={{ color: "var(--text-muted)" }}
                        onMouseEnter={(e) => (e.currentTarget.style.color = col.hoverColor)}
                        onMouseLeave={(e) => (e.currentTarget.style.color = "var(--text-muted)")}>
                        {l}
                      </a>
                    </li>
                  ))}
                </ul>
              </div>
            ))}
          </div>

          <div className="mt-12 flex flex-col items-center justify-between gap-4 border-t pt-8 text-xs sm:flex-row"
            style={{ borderColor: "rgba(255,255,255,0.06)", color: "var(--text-muted)" }}>
            <span>© 2026 Planora AI. All rights reserved.</span>
            <div className="flex items-center gap-1.5">
              <span>Built with</span>
              <span style={{ color: "#ff6b9d" }}>♥</span>
              <span>using Groq LLaMA 3.3 · Next.js · Leaflet · Open-Meteo</span>
            </div>
          </div>
        </div>
      </footer>
    </main>
  );
}